---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[chef-platform-provision::default]
    attributes:
