name 'chef-platform-provision'
maintainer 'Zack Zondlo'
maintainer_email 'zzondlo@chef.io'
license 'all_rights'
description 'Installs/Configures chef-platform-provision'
long_description 'Installs/Configures chef-platform-provision'
version '0.1.0'
